---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- certificate.yaml
- secret.yaml
- ingress.yaml

patches:
  - target: { kind: Deployment, labelSelector: app=simple-registry }
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          - name: tls
            projected:
              sources:
                - secret:
                    name: server-tls-certificate
                    items:
                      - key: tls.crt
                        path: server-certificate.pem
                      - key: tls.key
                        path: server-private-key.pem
  - target: { kind: Deployment, labelSelector: app=simple-registry }
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          - name: tls
            mountPath: /tls
            readOnly: true
