---
kind: Service
apiVersion: v1
metadata:
  name: valkey
  namespace: simple-registry
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
