---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: valkey-deployment
  namespace: simple-registry
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8.0.2
        ports:
        - containerPort: 6379
