---
kind: Secret
apiVersion: v1
metadata:
  name: simple-registry
  namespace: simple-registry
type: Opaque
stringData:
  config.toml: |
    [server]
    bind_address = "0.0.0.0"
    bind_port = 8000
    
    # [server.tls]
    # TLS is terminated by the ingress controller

    [lock_store.redis]
    url = "redis://valkey.simple-registry.svc:6379"
    key_prefix = "simple-registry-lock-"
    ttl = 5

    [cache_store.redis]
    url = "redis://valkey.simple-registry.svc:6379"
    key_prefix = "simple-registry-cache-"
    
    [storage.s3]
    access_key_id = "access-key-id"
    secret_key = "secret-key"
    endpoint = "https://sos-ch-gva-2.exo.io"
    bucket = "my-registry"
    region = "ch-gva-2"

    [[repository."hub".upstream]]
    url = "https://registry-1.docker.io"

    [repository."hub".access_policy]
    default_allow = true

    [[repository."ghcr".upstream]]
    url = "https://ghcr.io"

    [repository."ghcr".access_policy]
    default_allow = true
