[server]
bind_address = "0.0.0.0"
port = 8000

[server.tls]
server_certificate_bundle = "tls.d/server-ca-bundle.pem"
server_private_key = "tls.d/server-private-key.pem"
client_ca_bundle   = "tls.d/client-ca-bundle.pem"

[blob_store.fs]
root_dir = "./data-simple-registry"

#[blob_store.s3]
#access_key_id = "<key-id>"
#secret_key = "<secret-key>"
#endpoint = "https://<s3-compatible-endpoint>"
#bucket = "<bucket>"
#region = "<zone/region>"
#multipart_copy_threshold = "5GiB"
#multipart_copy_chunk_size = "100MiB"
#multipart_copy_jobs = 10

[observability.tracing]
endpoint = "http://127.0.0.1:4317"
sampling_rate = 1.0

[identity.phil]
username = "philippe"
password = "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$lurg6dYCXXrJP3zaFwu35w" # test

[repository."nginx"]

[repository."nginx".access_policy]
default_allow = true

[repository."test".access_policy]
default_allow = false
policies = [
    'identity.username in ["philippe"]',
    '"philippe" in identity.certificate.common_names',
    '"admins" in identity.certificate.organizations',
    """identity.id == "phil" && (request.action in [
    "get-api-version",
    "put-blob", "get-blob", "delete-blob",
    "put-manifest", "get-manifest", "delete-manifest",
    "get-referrers",
    "list-catalog",
    "list-tags"])"""
]
