---
kind: Secret
apiVersion: v1
metadata:
  name: simple-registry-config
  namespace: simple-registry
type: Opaque
stringData:
  config.toml: |
    [server]
    bind_address = "0.0.0.0"
    bind_port = 8000
    
    [server.tls]
    server_certificate_bundle = "/tls/server-certificate.pem"
    server_private_key = "/tls/server-private-key.pem"
    client_ca_bundle   = "/tls/client-ca-certificate.pem"

    [cache.redis]
    url = "redis://valkey.simple-registry.svc:6379"
    key_prefix = "simple-registry-cache-"
    
    [blob_store.s3]
    access_key_id = "access-key-id"
    secret_key = "secret-key"
    endpoint = "https://sos-ch-gva-2.exo.io"
    bucket = "my-registry"
    region = "ch-gva-2"
    
    [metadata_store.s3]
    access_key_id = "access-key-id"
    secret_key = "secret-key"
    endpoint = "https://sos-ch-gva-2.exo.io"
    bucket = "my-registry"
    region = "ch-gva-2"

    [metadata_store.s3.redis]
    url = "redis://valkey.simple-registry.svc:6379"
    key_prefix = "simple-registry-lock-"
    ttl = 5

    [[repository."hub".upstream]]
    url = "https://registry-1.docker.io"

    [repository."hub".access_policy]
    default_allow = true

    [[repository."ghcr".upstream]]
    url = "https://ghcr.io"

    [repository."ghcr".access_policy]
    default_allow = true
