---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: simple-registry
  namespace: simple-registry
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`cr.example.com`)
      service:
        name: simple-registry
        port:
          number: 8000

  tls:
    passthrough: true
