name: Conformance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: conformance

jobs:
  build-conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build conformance tool
        run: |
          git clone https://github.com/opencontainers/distribution-spec.git distribution-spec

          cd distribution-spec/conformance && \
            go test -c && \
            mv conformance.test ../.. && \
            cd ../..

      - name: Build the container
        run: |
          docker build -t ${IMAGE_NAME} -f Dockerfile --build-arg RELEASE_MODE=debug .

      - name: Run the conformance test (filesystem backend)
        run: |
          docker run --rm -d \
            -v ./conformance/config-fs.toml:/config.toml \
            --network host \
            --name conformance-fs-backend \
            ${IMAGE_NAME} \
            server

          source ./conformance/conformance-variables
          ./conformance.test

          docker stop conformance-fs-backend

      - name: Run the conformance test (s3 backend)
        run: |
          mkdir -p ./conformance/minio-data/registry
          docker run --rm -d \
            -v ./conformance/minio-data:/data \
            -e MINIO_ROOT_USER=root \
            -e MINIO_ROOT_PASSWORD=roottoor \
            -e MINIO_VOLUMES=/data \
            --network host \
            --name minio-server \
            quay.io/minio/minio \
            minio server /data

          for i in {1..10}; do
            if nc -z -w 3 127.0.0.1 9000; then
              break
            fi
            sleep 1
          done
          if [ $i -eq 10 ]; then
            echo "Minio did not start within 10 seconds"
            exit 1
          fi

          docker run --rm -d \
            -v ./conformance/config-s3.toml:/config.toml \
            --network host \
            --name conformance-s3-backend \
            ${IMAGE_NAME} \
            server
          
          for i in {1..10}; do
            if nc -z -w 3 127.0.0.1 8000; then
              break
            fi
            sleep 1
          done
          if [ $i -eq 10 ]; then
            echo "simple-registry did not start within 10 seconds"
            exit 1
          fi

          source ./conformance/conformance-variables
          ./conformance.test

          docker stop conformance-s3-backend
          docker stop minio-server
